apiVersion: app.bigkevmcd.com/v1alpha1
kind: Application
metadata:
  name: example-application
spec:
  processes:
    - name: web
      image: nginx:1.17.4
      port: 80
      replicas: 2
  environment:
    DATABASE_URL: postgres://localhost:5432/test-database
