apiVersion: app.bigkevmcd.com/v1alpha1
kind: Application
metadata:
  name: example-application
spec:
  replicas: 3
  labels:
    service: my-test-service
  containers:
    - name: nginx
      image: nginx:1.17.4
      ports:
      - containerPort: 80
  config:
    DATABASE_URL: postgres://localhost:5432/test-database
