apiVersion: apps/v1
kind: Deployment
metadata:
  name: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      name: applications
  template:
    metadata:
      labels:
        name: applications
    spec:
      serviceAccountName: applications
      containers:
        - name: applications
          image: quay.io/bigkevmcd/app-operator:latest
          command:
          - applications
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "applications"
