kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: applications
subjects:
- kind: ServiceAccount
  name: applications
roleRef:
  kind: Role
  name: applications
  apiGroup: rbac.authorization.k8s.io
